spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/disney?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: mysql
server:
 port: 8081